# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_telemetry_wins(object):
    def setupUi(self, telemetry_wins):
        telemetry_wins.setObjectName("telemetry_wins")
        telemetry_wins.resize(997, 668)
        self.centralwidget = QtWidgets.QWidget(telemetry_wins)
        self.centralwidget.setObjectName("centralwidget")
        self.main_title = QtWidgets.QLabel(self.centralwidget)
        self.main_title.setGeometry(QtCore.QRect(340, 10, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.main_title.setFont(font)
        self.main_title.setObjectName("main_title")
        self.recvtel_labe = QtWidgets.QLabel(self.centralwidget)
        self.recvtel_labe.setGeometry(QtCore.QRect(200, 100, 161, 17))
        self.recvtel_labe.setObjectName("recvtel_labe")
        self.telemet_combo = QtWidgets.QComboBox(self.centralwidget)
        self.telemet_combo.setGeometry(QtCore.QRect(100, 140, 351, 25))
        self.telemet_combo.setObjectName("telemet_combo")
        self.tpw_labe = QtWidgets.QLabel(self.centralwidget)
        self.tpw_labe.setGeometry(QtCore.QRect(160, 220, 241, 17))
        self.tpw_labe.setObjectName("tpw_labe")
        self.ack_labe = QtWidgets.QLabel(self.centralwidget)
        self.ack_labe.setGeometry(QtCore.QRect(210, 400, 101, 17))
        self.ack_labe.setObjectName("ack_labe")
        self.ack_win = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ack_win.setGeometry(QtCore.QRect(20, 430, 541, 121))
        self.ack_win.setObjectName("ack_win")
        self.tpw_win = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tpw_win.setGeometry(QtCore.QRect(20, 250, 541, 131))
        self.tpw_win.setObjectName("tpw_win")
        self.tusw_labe = QtWidgets.QLabel(self.centralwidget)
        self.tusw_labe.setGeometry(QtCore.QRect(650, 90, 271, 20))
        self.tusw_labe.setObjectName("tusw_labe")
        self.sep_line = QtWidgets.QFrame(self.centralwidget)
        self.sep_line.setGeometry(QtCore.QRect(560, 40, 31, 601))
        self.sep_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.sep_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sep_line.setObjectName("sep_line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 570, 501, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ext_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ext_btn.setObjectName("ext_btn")
        self.horizontalLayout.addWidget(self.ext_btn)
        self.recv_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.recv_btn.setObjectName("recv_btn")
        self.horizontalLayout.addWidget(self.recv_btn)
        self.verify_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.verify_btn.setObjectName("verify_btn")
        self.horizontalLayout.addWidget(self.verify_btn)
        self.bat_sta = QtWidgets.QLabel(self.centralwidget)
        self.bat_sta.setGeometry(QtCore.QRect(730, 140, 121, 17))
        self.bat_sta.setObjectName("bat_sta")
        self.bat_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.bat_bar.setGeometry(QtCore.QRect(600, 180, 381, 23))
        self.bat_bar.setProperty("value", 24)
        self.bat_bar.setObjectName("bat_bar")
        self.hlt_labe = QtWidgets.QLabel(self.centralwidget)
        self.hlt_labe.setGeometry(QtCore.QRect(730, 220, 131, 17))
        self.hlt_labe.setObjectName("hlt_labe")
        self.hlth_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.hlth_bar.setGeometry(QtCore.QRect(600, 260, 381, 23))
        self.hlth_bar.setProperty("value", 24)
        self.hlth_bar.setObjectName("hlth_bar")
        self.time_labe = QtWidgets.QLabel(self.centralwidget)
        self.time_labe.setGeometry(QtCore.QRect(730, 300, 131, 17))
        self.time_labe.setObjectName("time_labe")
        self.time_box = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_box.setGeometry(QtCore.QRect(600, 340, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.time_box.setFont(font)
        self.time_box.setAutoFillBackground(False)
        self.time_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.time_box.setSmallDecimalPoint(False)
        self.time_box.setProperty("value", 100.0)
        self.time_box.setObjectName("time_box")
        self.img_labe = QtWidgets.QLabel(self.centralwidget)
        self.img_labe.setGeometry(QtCore.QRect(700, 410, 181, 17))
        self.img_labe.setObjectName("img_labe")
        self.img_win = QtWidgets.QLabel(self.centralwidget)
        self.img_win.setGeometry(QtCore.QRect(610, 450, 361, 191))
        self.img_win.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.img_win.setText("")
        self.img_win.setObjectName("img_win")
        telemetry_wins.setCentralWidget(self.centralwidget)

        self.retranslateUi(telemetry_wins)
        QtCore.QMetaObject.connectSlotsByName(telemetry_wins)

    def retranslateUi(self, telemetry_wins):
        _translate = QtCore.QCoreApplication.translate
        telemetry_wins.setWindowTitle(_translate("telemetry_wins", "TELEMETRY SIMULATION"))
        self.main_title.setText(_translate("telemetry_wins", "TELEMETRY SIMULATION WINDOW"))
        self.recvtel_labe.setText(_translate("telemetry_wins", "RECEVING TELEMETRY"))
        self.tpw_labe.setText(_translate("telemetry_wins", "TELEMETRY PROCESSING WINDOW"))
        self.ack_labe.setText(_translate("telemetry_wins", "ACK WINDOW"))
        self.tusw_labe.setText(_translate("telemetry_wins", "TELEMETRY UPDATE STATUS  WINDOW"))
        self.ext_btn.setText(_translate("telemetry_wins", "Exit"))
        self.recv_btn.setText(_translate("telemetry_wins", "Receive"))
        self.verify_btn.setText(_translate("telemetry_wins", "Verify"))
        self.bat_sta.setText(_translate("telemetry_wins", "BATTERY STATUS"))
        self.hlt_labe.setText(_translate("telemetry_wins", "SATELLITE HEALTH"))
        self.time_labe.setText(_translate("telemetry_wins", "SPACE TIME (DAY)"))
        self.img_labe.setText(_translate("telemetry_wins", "SATELLITE STATUS IMAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telemetry_wins = QtWidgets.QMainWindow()
    ui = Ui_telemetry_wins()
    ui.setupUi(telemetry_wins)
    telemetry_wins.show()
    sys.exit(app.exec_())

